// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WizardGame.DataAccess;

namespace WizardGame.DataAccess.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20210502133349_Added ConfigurationName")]
    partial class AddedConfigurationName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WizardGame.Model.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayMode")
                        .HasColumnType("int");

                    b.Property<string>("Interact1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interact2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interact3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveDown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveUp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavContinue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavPause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Configurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action1 = "LEFTARROW",
                            Action2 = "UPARROW",
                            Action3 = "RIGHTARROW",
                            Action4 = "DOWNARROW",
                            ConfigurationName = "Default Configuration",
                            DisplayMode = 0,
                            Interact1 = "R",
                            Interact2 = "F",
                            Interact3 = "C",
                            MoveDown = "S",
                            MoveLeft = "A",
                            MoveRight = "D",
                            MoveUp = "W",
                            NavBack = "BACKSPACE",
                            NavContinue = "ENTER",
                            NavPause = "ESCAPE",
                            Volume = 50
                        },
                        new
                        {
                            Id = 2,
                            Action1 = "A",
                            Action2 = "W",
                            Action3 = "D",
                            Action4 = "S",
                            ConfigurationName = "Switch",
                            DisplayMode = 0,
                            Interact1 = "R",
                            Interact2 = "F",
                            Interact3 = "C",
                            MoveDown = "UPARROW",
                            MoveLeft = "LEFTARROW",
                            MoveRight = "RIGHTARROW",
                            MoveUp = "DOWNARROW",
                            NavBack = "BACKSPACE",
                            NavContinue = "ENTER",
                            NavPause = "ESCAPE",
                            Volume = 50
                        },
                        new
                        {
                            Id = 3,
                            Action1 = "LEFTARROW",
                            Action2 = "UPARROW",
                            Action3 = "RIGHTARROW",
                            Action4 = "DOWNARROW",
                            ConfigurationName = "Windowed Borderless",
                            DisplayMode = 1,
                            Interact1 = "R",
                            Interact2 = "F",
                            Interact3 = "C",
                            MoveDown = "S",
                            MoveLeft = "A",
                            MoveRight = "D",
                            MoveUp = "W",
                            NavBack = "BACKSPACE",
                            NavContinue = "ENTER",
                            NavPause = "ESCAPE",
                            Volume = 50
                        },
                        new
                        {
                            Id = 4,
                            Action1 = "LEFTARROW",
                            Action2 = "UPARROW",
                            Action3 = "RIGHTARROW",
                            Action4 = "DOWNARROW",
                            ConfigurationName = "Fullscreen",
                            DisplayMode = 2,
                            Interact1 = "R",
                            Interact2 = "F",
                            Interact3 = "C",
                            MoveDown = "S",
                            MoveLeft = "A",
                            MoveRight = "D",
                            MoveUp = "W",
                            NavBack = "BACKSPACE",
                            NavContinue = "ENTER",
                            NavPause = "ESCAPE",
                            Volume = 50
                        },
                        new
                        {
                            Id = 5,
                            Action1 = "NUMLEFT",
                            Action2 = "NUMUP",
                            Action3 = "NUMRIGHT",
                            Action4 = "NUMDOWN",
                            ConfigurationName = "NumPad",
                            DisplayMode = 0,
                            Interact1 = "R",
                            Interact2 = "F",
                            Interact3 = "C",
                            MoveDown = "S",
                            MoveLeft = "A",
                            MoveRight = "D",
                            MoveUp = "W",
                            NavBack = "BACKSPACE",
                            NavContinue = "ENTER",
                            NavPause = "ESCAPE",
                            Volume = 50
                        },
                        new
                        {
                            Id = 6,
                            Action1 = "N",
                            Action2 = "J",
                            Action3 = "K",
                            Action4 = "M",
                            ConfigurationName = "Close Together",
                            DisplayMode = 0,
                            Interact1 = "R",
                            Interact2 = "F",
                            Interact3 = "C",
                            MoveDown = "S",
                            MoveLeft = "A",
                            MoveRight = "D",
                            MoveUp = "W",
                            NavBack = "BACKSPACE",
                            NavContinue = "ENTER",
                            NavPause = "ESCAPE",
                            Volume = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
