// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WizardGame.DataAccess;

namespace WizardGame.DataAccess.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20210501203758_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WizardGame.Model.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayMode")
                        .HasColumnType("int");

                    b.Property<string>("Interact1")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Interact2")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Interact3")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MoveDown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveUp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavContinue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavPause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
